/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ConsultancyDto } from '../model/consultancy-dto';
// @ts-ignore
import { ConsultancyDtoListResult } from '../model/consultancy-dto-list-result';
// @ts-ignore
import { ConsultancyDtoResult } from '../model/consultancy-dto-result';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class ConsultancyService {

    protected basePath = 'https://hiresapi.azurewebsites.net';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string|string[], @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (Array.isArray(basePath) && basePath.length > 0) {
                basePath = basePath[0];
            }

            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }

    // @ts-ignore
    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param imgImageFile 
     * @param consultancyForInsertDtoName 
     * @param consultancyForInsertDtoEmail 
     * @param consultancyForInsertDtoAddress 
     * @param consultancyForInsertDtoPhone 
     * @param consultancyForInsertDtoActive 
     * @param consultancyForInsertDtoUpdated 
     * @param consultancyForInsertDtoWebsite 
     * @param consultancyForInsertDtoLinkedin 
     * @param consultancyForInsertDtoLogo 
     * @param consultancyForInsertDtoCityId 
     * @param consultancyForInsertDtoDomainname 
     * @param consultancyForInsertDtoUpdatedBy 
     * @param consultancyForInsertDtoIsDirectCompany 
     * @param consultancyForInsertDtoStatusId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiConsultancyAddPost(imgImageFile?: Blob, consultancyForInsertDtoName?: string, consultancyForInsertDtoEmail?: string, consultancyForInsertDtoAddress?: string, consultancyForInsertDtoPhone?: string, consultancyForInsertDtoActive?: boolean, consultancyForInsertDtoUpdated?: string, consultancyForInsertDtoWebsite?: string, consultancyForInsertDtoLinkedin?: string, consultancyForInsertDtoLogo?: string, consultancyForInsertDtoCityId?: number, consultancyForInsertDtoDomainname?: string, consultancyForInsertDtoUpdatedBy?: number, consultancyForInsertDtoIsDirectCompany?: boolean, consultancyForInsertDtoStatusId?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<ConsultancyDtoResult>;
    public apiConsultancyAddPost(imgImageFile?: Blob, consultancyForInsertDtoName?: string, consultancyForInsertDtoEmail?: string, consultancyForInsertDtoAddress?: string, consultancyForInsertDtoPhone?: string, consultancyForInsertDtoActive?: boolean, consultancyForInsertDtoUpdated?: string, consultancyForInsertDtoWebsite?: string, consultancyForInsertDtoLinkedin?: string, consultancyForInsertDtoLogo?: string, consultancyForInsertDtoCityId?: number, consultancyForInsertDtoDomainname?: string, consultancyForInsertDtoUpdatedBy?: number, consultancyForInsertDtoIsDirectCompany?: boolean, consultancyForInsertDtoStatusId?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpResponse<ConsultancyDtoResult>>;
    public apiConsultancyAddPost(imgImageFile?: Blob, consultancyForInsertDtoName?: string, consultancyForInsertDtoEmail?: string, consultancyForInsertDtoAddress?: string, consultancyForInsertDtoPhone?: string, consultancyForInsertDtoActive?: boolean, consultancyForInsertDtoUpdated?: string, consultancyForInsertDtoWebsite?: string, consultancyForInsertDtoLinkedin?: string, consultancyForInsertDtoLogo?: string, consultancyForInsertDtoCityId?: number, consultancyForInsertDtoDomainname?: string, consultancyForInsertDtoUpdatedBy?: number, consultancyForInsertDtoIsDirectCompany?: boolean, consultancyForInsertDtoStatusId?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpEvent<ConsultancyDtoResult>>;
    public apiConsultancyAddPost(imgImageFile?: Blob, consultancyForInsertDtoName?: string, consultancyForInsertDtoEmail?: string, consultancyForInsertDtoAddress?: string, consultancyForInsertDtoPhone?: string, consultancyForInsertDtoActive?: boolean, consultancyForInsertDtoUpdated?: string, consultancyForInsertDtoWebsite?: string, consultancyForInsertDtoLinkedin?: string, consultancyForInsertDtoLogo?: string, consultancyForInsertDtoCityId?: number, consultancyForInsertDtoDomainname?: string, consultancyForInsertDtoUpdatedBy?: number, consultancyForInsertDtoIsDirectCompany?: boolean, consultancyForInsertDtoStatusId?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (Bearer) required
        localVarCredential = this.configuration.lookupCredential('Bearer');
        if (localVarCredential) {
            localVarHeaders = localVarHeaders.set('Authorization', localVarCredential);
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/plain',
                'application/json',
                'text/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (imgImageFile !== undefined) {
            localVarFormParams = localVarFormParams.append('img.ImageFile', <any>imgImageFile) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoName !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Name', <any>consultancyForInsertDtoName) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoEmail !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Email', <any>consultancyForInsertDtoEmail) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoAddress !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Address', <any>consultancyForInsertDtoAddress) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoPhone !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Phone', <any>consultancyForInsertDtoPhone) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoActive !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Active', <any>consultancyForInsertDtoActive) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoUpdated !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Updated', <any>consultancyForInsertDtoUpdated) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoWebsite !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Website', <any>consultancyForInsertDtoWebsite) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoLinkedin !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Linkedin', <any>consultancyForInsertDtoLinkedin) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoLogo !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Logo', <any>consultancyForInsertDtoLogo) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoCityId !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.CityId', <any>consultancyForInsertDtoCityId) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoDomainname !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.Domainname', <any>consultancyForInsertDtoDomainname) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoUpdatedBy !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.UpdatedBy', <any>consultancyForInsertDtoUpdatedBy) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoIsDirectCompany !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.IsDirectCompany', <any>consultancyForInsertDtoIsDirectCompany) as any || localVarFormParams;
        }
        if (consultancyForInsertDtoStatusId !== undefined) {
            localVarFormParams = localVarFormParams.append('consultancyForInsertDto.StatusId', <any>consultancyForInsertDtoStatusId) as any || localVarFormParams;
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/Consultancy/Add`;
        return this.httpClient.request<ConsultancyDtoResult>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiConsultancyAllConsultancyGet(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<ConsultancyDtoListResult>;
    public apiConsultancyAllConsultancyGet(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpResponse<ConsultancyDtoListResult>>;
    public apiConsultancyAllConsultancyGet(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpEvent<ConsultancyDtoListResult>>;
    public apiConsultancyAllConsultancyGet(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (Bearer) required
        localVarCredential = this.configuration.lookupCredential('Bearer');
        if (localVarCredential) {
            localVarHeaders = localVarHeaders.set('Authorization', localVarCredential);
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/plain',
                'application/json',
                'text/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/Consultancy/AllConsultancy`;
        return this.httpClient.request<ConsultancyDtoListResult>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiConsultancyConsultancyByIdGet(id?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<ConsultancyDtoResult>;
    public apiConsultancyConsultancyByIdGet(id?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpResponse<ConsultancyDtoResult>>;
    public apiConsultancyConsultancyByIdGet(id?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpEvent<ConsultancyDtoResult>>;
    public apiConsultancyConsultancyByIdGet(id?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (id !== undefined && id !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>id, 'Id');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (Bearer) required
        localVarCredential = this.configuration.lookupCredential('Bearer');
        if (localVarCredential) {
            localVarHeaders = localVarHeaders.set('Authorization', localVarCredential);
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/plain',
                'application/json',
                'text/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/Consultancy/ConsultancyById`;
        return this.httpClient.request<ConsultancyDtoResult>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param conname 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiConsultancySearchConsultanciesGet(conname?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<ConsultancyDtoListResult>;
    public apiConsultancySearchConsultanciesGet(conname?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpResponse<ConsultancyDtoListResult>>;
    public apiConsultancySearchConsultanciesGet(conname?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpEvent<ConsultancyDtoListResult>>;
    public apiConsultancySearchConsultanciesGet(conname?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (conname !== undefined && conname !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>conname, 'conname');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (Bearer) required
        localVarCredential = this.configuration.lookupCredential('Bearer');
        if (localVarCredential) {
            localVarHeaders = localVarHeaders.set('Authorization', localVarCredential);
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/plain',
                'application/json',
                'text/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/Consultancy/SearchConsultancies`;
        return this.httpClient.request<ConsultancyDtoListResult>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param consultancyDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiConsultancyUpdatePut(consultancyDto?: ConsultancyDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<ConsultancyDtoResult>;
    public apiConsultancyUpdatePut(consultancyDto?: ConsultancyDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpResponse<ConsultancyDtoResult>>;
    public apiConsultancyUpdatePut(consultancyDto?: ConsultancyDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpEvent<ConsultancyDtoResult>>;
    public apiConsultancyUpdatePut(consultancyDto?: ConsultancyDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        let localVarCredential: string | undefined;
        // authentication (Bearer) required
        localVarCredential = this.configuration.lookupCredential('Bearer');
        if (localVarCredential) {
            localVarHeaders = localVarHeaders.set('Authorization', localVarCredential);
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'text/plain',
                'application/json',
                'text/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/Consultancy/Update`;
        return this.httpClient.request<ConsultancyDtoResult>('put', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: consultancyDto,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
