/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CandidateProfileSkillDto { 
    id?: number | null;
    candidateProfileid?: number | null;
    skillId?: number | null;
    name?: string | null;
    active?: boolean | null;
    proficiencyLevel?: number | null;
    yearsOfExp?: number | null;
}

