/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidatePrefLocationDto } from './candidate-pref-location-dto';
import { CandidateProfileSkillDto } from './candidate-profile-skill-dto';
import { CandidateProfileEmploymentTypeDto } from './candidate-profile-employment-type-dto';
import { CandidateDocumentDto } from './candidate-document-dto';
import { CandidateProfileDomainDto } from './candidate-profile-domain-dto';
import { CandidatePrefJobTypeDto } from './candidate-pref-job-type-dto';
import { CityDto } from './city-dto';


export interface CandidateProfileDto { 
    id?: number | null;
    userId?: number;
    consultancyUserId?: number | null;
    candidateName?: string | null;
    title?: string | null;
    active?: boolean | null;
    postedDate?: string | null;
    canRelocate?: boolean | null;
    totalExp?: number | null;
    statusId?: number;
    linkedIn?: string | null;
    resume?: string | null;
    availability?: number | null;
    visaId?: number | null;
    visaExpiryDate?: string | null;
    passportno?: string | null;
    firstArrivalDate?: string | null;
    backgroundchecked?: boolean | null;
    cityId?: number | null;
    remoteOnly?: boolean | null;
    anyLocation?: boolean | null;
    comment?: string | null;
    employerInfo?: string | null;
    fromAmt?: number | null;
    toAmt?: number | null;
    email?: string | null;
    phone?: string | null;
    consultingRoleId?: number | null;
    readonly candidateDocuments?: Array<CandidateDocumentDto> | null;
    candidatePrefJobTypes?: Array<CandidatePrefJobTypeDto> | null;
    candidatePrefLocations?: Array<CandidatePrefLocationDto> | null;
    candidateProfileDomains?: Array<CandidateProfileDomainDto> | null;
    candidateProfileEmploymentTypes?: Array<CandidateProfileEmploymentTypeDto> | null;
    candidateProfileSkills?: Array<CandidateProfileSkillDto> | null;
    city?: CityDto;
}

