/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidateProfileSkillForUpdateDto } from './candidate-profile-skill-for-update-dto';
import { CandidateProfileEmploymentTypeDtoForUpdate } from './candidate-profile-employment-type-dto-for-update';
import { CandidatePrefLocationDtoForUpdate } from './candidate-pref-location-dto-for-update';
import { CandidatePrefJobTypeDtoForUpdate } from './candidate-pref-job-type-dto-for-update';
import { CandidateProfileDomainDtoForUpdate } from './candidate-profile-domain-dto-for-update';
import { CandidateDocumentDtoForUpdate } from './candidate-document-dto-for-update';


export interface CandidateProfileDtoForUpdate { 
    id?: number | null;
    userId?: number;
    consultancyUserId?: number | null;
    candidateName?: string | null;
    title?: string | null;
    active?: boolean | null;
    postedDate?: string | null;
    canRelocate?: boolean | null;
    totalExp?: number | null;
    statusId?: number;
    linkedIn?: string | null;
    resume?: string | null;
    availability?: number | null;
    visaId?: number | null;
    visaExpiryDate?: string | null;
    passportno?: string | null;
    firstArrivalDate?: string | null;
    backgroundchecked?: boolean | null;
    cityId?: number | null;
    remoteOnly?: boolean | null;
    anyLocation?: boolean | null;
    comment?: string | null;
    employerInfo?: string | null;
    fromAmt?: number | null;
    toAmt?: number | null;
    email?: string | null;
    phone?: string | null;
    consultingRoleId?: number | null;
    candidateDocuments?: Array<CandidateDocumentDtoForUpdate> | null;
    candidatePrefJobTypes?: Array<CandidatePrefJobTypeDtoForUpdate> | null;
    candidatePrefLocations?: Array<CandidatePrefLocationDtoForUpdate> | null;
    candidateProfileDomains?: Array<CandidateProfileDomainDtoForUpdate> | null;
    candidateProfileEmploymentTypes?: Array<CandidateProfileEmploymentTypeDtoForUpdate> | null;
    candidateProfileSkills?: Array<CandidateProfileSkillForUpdateDto> | null;
}

