/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CandidatePrefLocationDto { 
    id?: number | null;
    candidateId?: number | null;
    cityId?: number | null;
    cityName?: string | null;
    stateName?: string | null;
    stateCode?: string | null;
}

