/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CandidateProfileEmploymentTypeDto { 
    id?: number | null;
    candidateProfileId?: number | null;
    employmentTypeId?: number | null;
    employmentTypeName?: string | null;
    active?: boolean | null;
}

