/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidatePrefLocationDto } from './candidate-pref-location-dto';
import { CandidateProfileSkillDto } from './candidate-profile-skill-dto';
import { VisaDto } from './visa-dto';
import { CandidateDocumentDto } from './candidate-document-dto';
import { CityDto } from './city-dto';


export interface CandidateProfileSimplelistDto { 
    id?: number;
    candidateName?: string | null;
    title?: string | null;
    canRelocate?: boolean | null;
    totalExp?: number | null;
    linkedIn?: string | null;
    visaId?: number | null;
    cityId?: number | null;
    remoteOnly?: boolean | null;
    email?: string | null;
    phone?: string | null;
    readonly candidateDocuments?: Array<CandidateDocumentDto> | null;
    candidatePrefLocations?: Array<CandidatePrefLocationDto> | null;
    candidateProfileSkills?: Array<CandidateProfileSkillDto> | null;
    city?: CityDto;
    visa?: VisaDto;
}

