/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CandidatePrefJobTypeDtoForUpdate { 
    id?: number | null;
    candidateProfileId?: number | null;
    jobTypeId?: number | null;
}

