/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CandidateProfileSkillForInsertDto } from './candidate-profile-skill-for-insert-dto';
import { CandidatePrefJobTypeForInsertDto } from './candidate-pref-job-type-for-insert-dto';
import { CandidateProfileDomainForInsertDto } from './candidate-profile-domain-for-insert-dto';
import { CandidatePrefLocationForInsertDto } from './candidate-pref-location-for-insert-dto';
import { CandidateProfileEmploymentTypeForInsertDto } from './candidate-profile-employment-type-for-insert-dto';


export interface CandidateProfileForInsertDto { 
    id?: number | null;
    userId?: number;
    consultancyUserId?: number | null;
    candidateName?: string | null;
    title?: string | null;
    active?: boolean | null;
    postedDate?: string | null;
    canRelocate?: boolean | null;
    totalExp?: number | null;
    statusId?: number;
    linkedIn?: string | null;
    resume?: string | null;
    availability?: number | null;
    visaId?: number | null;
    visaExpiryDate?: string | null;
    passportno?: string | null;
    firstArrivalDate?: string | null;
    backgroundchecked?: boolean | null;
    cityId?: number | null;
    remoteOnly?: boolean | null;
    anyLocation?: boolean | null;
    comment?: string | null;
    employerInfo?: string | null;
    fromAmt?: number | null;
    toAmt?: number | null;
    email?: string | null;
    phone?: string | null;
    consultingRoleId?: number | null;
    candidatePrefJobTypes?: Array<CandidatePrefJobTypeForInsertDto> | null;
    candidatePrefLocations?: Array<CandidatePrefLocationForInsertDto> | null;
    candidateProfileDomains?: Array<CandidateProfileDomainForInsertDto> | null;
    candidateProfileEmploymentTypes?: Array<CandidateProfileEmploymentTypeForInsertDto> | null;
    candidateProfileSkills?: Array<CandidateProfileSkillForInsertDto> | null;
}

