/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StateDto } from './state-dto';


export interface CityDto { 
    id?: number;
    idState?: number;
    city1?: string | null;
    zip?: string | null;
    stateCode?: string | null;
    stateName?: string | null;
    countryName?: string | null;
    idStateNavigation?: StateDto;
}

