/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsultancyDto } from './consultancy-dto';
import { UserDto } from './user-dto';


export interface ConsultancyUserDto { 
    id?: number;
    consultancyId?: number | null;
    active?: boolean | null;
    updated?: string | null;
    publicProfileUserName?: string | null;
    userId?: number;
    noOfViews?: number | null;
    parentId?: number | null;
    noOfPosting?: number | null;
    updatedBy?: number | null;
    user?: UserDto;
    consultancy?: ConsultancyDto;
}

