/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsultancyDto { 
    id?: number;
    name?: string | null;
    email?: string | null;
    address?: string | null;
    phone?: string | null;
    active?: boolean | null;
    updated?: string | null;
    website?: string | null;
    linkedin?: string | null;
    logo?: string | null;
    cityId?: number | null;
    domainname?: string | null;
    updatedBy?: number | null;
    isDirectCompany?: boolean | null;
    statusId?: number | null;
}

