/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DomainDto { 
    id?: number;
    name?: string | null;
    description?: string | null;
    updatedBy?: number | null;
    updated?: string | null;
}

