/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobOpeningEmploymentTypeDto } from './job-opening-employment-type-dto';
import { JobOpeningLocationDto } from './job-opening-location-dto';
import { JobOpeningSkillDto } from './job-opening-skill-dto';
import { JobOpeningJobTypeDto } from './job-opening-job-type-dto';
import { JobOpeningVisaMapDto } from './job-opening-visa-map-dto';


export interface JobOpeningDto { 
    id?: number;
    name?: string | null;
    country?: string | null;
    joiningdays?: number | null;
    description?: string | null;
    totalExp?: number | null;
    postedDate?: string | null;
    lastDate?: string | null;
    numberOfOpening?: number | null;
    active?: boolean | null;
    consultancyUserId?: number | null;
    priorityId?: number | null;
    categoryId?: number | null;
    jobLocation?: string | null;
    postalcode?: string | null;
    projectStartId?: number | null;
    directClient?: boolean | null;
    isReviewed?: boolean | null;
    fromAmt?: number | null;
    toAmt?: number | null;
    notifyOnCandidateProfileMap?: boolean | null;
    notifyWithResume?: boolean | null;
    localCandidatePref?: boolean | null;
    localCandidateOnly?: boolean | null;
    isExpired?: boolean | null;
    jobOpeningSkills?: Array<JobOpeningSkillDto> | null;
    jobOpeningVisaMaps?: Array<JobOpeningVisaMapDto> | null;
    jobOpeningLocations?: Array<JobOpeningLocationDto> | null;
    jobOpeningEmploymentTypes?: Array<JobOpeningEmploymentTypeDto> | null;
    jobOpeningJobTypes?: Array<JobOpeningJobTypeDto> | null;
}

