/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmploymentTypeDto } from './employment-type-dto';


export interface JobOpeningEmploymentTypeDto { 
    id?: number;
    jobOpeningId?: number | null;
    employmentTypeId?: number | null;
    active?: boolean | null;
    employmentType?: EmploymentTypeDto;
}

