/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileCountSummary } from './profile-count-summary';
import { JobOpeningLocationDto } from './job-opening-location-dto';


export interface JobOpeningProfileMapSummary1 { 
    jobOpeningId?: number;
    profileCountSummary?: Array<ProfileCountSummary> | null;
    name?: string | null;
    description?: string | null;
    postDate?: string | null;
    jobLocation?: string | null;
    active?: boolean | null;
    jobOpeningLocation?: Array<JobOpeningLocationDto> | null;
}

