/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobOpeningCandidateProfileMapDto { 
    id?: number;
    jobOpeningId?: number;
    candidateProfileId?: number;
    appliedDate?: string | null;
    active?: boolean | null;
    candidateProfileMappingStatusId?: number;
    comment?: string | null;
    consultancyUserId?: number | null;
    candidateUserId?: number | null;
    doc?: string | null;
    candidateName?: string | null;
    totalYearsOfExp?: number | null;
    linkedIn?: string | null;
    currentLocationCityid?: number | null;
}

