/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CityDto } from './city-dto';


export interface JobOpeningLocationDto { 
    id?: number;
    jobOpeningId?: number;
    numberOfOpenings?: number | null;
    cityId?: number | null;
    city?: CityDto;
}

