/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobOpeningProfileMapSummary { 
    jobOpeningId?: number;
    candidateProfileMappingStatusId?: number;
    candidateProfileMappingStatusName?: string | null;
    count?: number;
    name?: string | null;
    description?: string | null;
    postDate?: string | null;
    jobLocation?: string | null;
    active?: boolean | null;
}

