/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobOpeningJobTypeForUpdateDto } from './job-opening-job-type-for-update-dto';
import { JobOpeningSkillForUpdateDto } from './job-opening-skill-for-update-dto';
import { JobOpeningVisaMapForUpdateDto } from './job-opening-visa-map-for-update-dto';
import { JobOpeningEmploymentTypeForUpdateDto } from './job-opening-employment-type-for-update-dto';
import { JobOpeningLocationForUpdateDto } from './job-opening-location-for-update-dto';


export interface JobOpeningDtoForUpdate { 
    id?: number | null;
    name?: string | null;
    country?: string | null;
    joiningdays?: number | null;
    description?: string | null;
    totalExp?: number | null;
    postedDate?: string | null;
    lastDate?: string | null;
    numberOfOpening?: number | null;
    active?: boolean | null;
    consultancyUserId?: number | null;
    priorityId?: number | null;
    categoryId?: number | null;
    jobLocation?: string | null;
    postalcode?: string | null;
    projectStartId?: number | null;
    directClient?: boolean | null;
    isReviewed?: boolean | null;
    fromAmt?: number | null;
    toAmt?: number | null;
    notifyOnCandidateProfileMap?: boolean | null;
    notifyWithResume?: boolean | null;
    localCandidatePref?: boolean | null;
    localCandidateOnly?: boolean | null;
    isExpired?: boolean | null;
    jobOpeningSkills?: Array<JobOpeningSkillForUpdateDto> | null;
    jobOpeningVisaMaps?: Array<JobOpeningVisaMapForUpdateDto> | null;
    jobOpeningLocations?: Array<JobOpeningLocationForUpdateDto> | null;
    jobOpeningEmploymentTypes?: Array<JobOpeningEmploymentTypeForUpdateDto> | null;
    jobOpeningJobTypes?: Array<JobOpeningJobTypeForUpdateDto> | null;
}

