/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsultancyUserDto } from './consultancy-user-dto';
import { CandidateProfileDto } from './candidate-profile-dto';
import { JobOpeningDto } from './job-opening-dto';
import { CityDto } from './city-dto';


export interface JobOpeningCandidateProfileDetailMapDto { 
    id?: number;
    jobOpeningId?: number;
    candidateProfileId?: number | null;
    appliedDate?: string | null;
    active?: boolean | null;
    candidateProfileMappingStatusId?: number;
    candidateProfileMappingStatusName?: string | null;
    comment?: string | null;
    updatedBy?: number | null;
    consultancyUserId?: number | null;
    candidateUserId?: number | null;
    updated?: string | null;
    candidateProfile?: CandidateProfileDto;
    consultancyUser?: ConsultancyUserDto;
    jobOpening?: JobOpeningDto;
    doc?: string | null;
    candidateName?: string | null;
    totalYearsOfExp?: number | null;
    linkedIn?: string | null;
    currentLocationCityid?: number | null;
    currentLocationCity?: CityDto;
}

