/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobOpeningProfileConsultancyCommentDto { 
    id?: number;
    jobopeningCandidateProfileMapId?: number;
    consultancyUserId?: number;
    comment?: string | null;
    active?: boolean | null;
    updated?: string | null;
}

