/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobTypeDto } from './job-type-dto';


export interface JobOpeningJobTypeDto { 
    id?: number;
    jobOpeningId?: number | null;
    jobTypeId?: number | null;
    active?: boolean | null;
    jobType?: JobTypeDto;
}

