/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobOpeningSkillForInsertDto } from './job-opening-skill-for-insert-dto';
import { JobOpeningVisaMapForInsertDto } from './job-opening-visa-map-for-insert-dto';
import { JobOpeningEmploymentTypeForInsertDto } from './job-opening-employment-type-for-insert-dto';
import { JobOpeningJobTypeForInsertDto } from './job-opening-job-type-for-insert-dto';
import { JobOpeningLocationForInsertDto } from './job-opening-location-for-insert-dto';


export interface JobOpeningForInsertDto { 
    name?: string | null;
    country?: string | null;
    joiningdays?: number | null;
    description?: string | null;
    totalExp?: number | null;
    postedDate?: string | null;
    lastDate?: string | null;
    numberOfOpening?: number | null;
    active?: boolean | null;
    consultancyUserId?: number | null;
    priorityId?: number | null;
    categoryId?: number | null;
    jobLocation?: string | null;
    postalcode?: string | null;
    projectStartId?: number | null;
    directClient?: boolean | null;
    isReviewed?: boolean | null;
    fromAmt?: number | null;
    toAmt?: number | null;
    notifyOnCandidateProfileMap?: boolean | null;
    notifyWithResume?: boolean | null;
    localCandidatePref?: boolean | null;
    localCandidateOnly?: boolean | null;
    isExpired?: boolean | null;
    jobOpeningSkills?: Array<JobOpeningSkillForInsertDto> | null;
    jobOpeningVisaMaps?: Array<JobOpeningVisaMapForInsertDto> | null;
    jobOpeningLocations?: Array<JobOpeningLocationForInsertDto> | null;
    jobOpeningEmploymentTypes?: Array<JobOpeningEmploymentTypeForInsertDto> | null;
    jobOpeningJobTypes?: Array<JobOpeningJobTypeForInsertDto> | null;
}

