/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginModel { 
    token?: string | null;
    userId?: number;
    userName?: string | null;
    userTypeId?: number;
    userTypeName?: string | null;
    consultancyId?: number | null;
    functions?: Array<string> | null;
    consultancyUserId?: number | null;
}

