/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsultancyUserDto } from './consultancy-user-dto';


export interface UserDtoForReturn { 
    id?: number;
    fname?: string | null;
    userName?: string | null;
    email?: string | null;
    cityId?: number | null;
    phone?: string | null;
    linkedin?: string | null;
    active?: boolean | null;
    profilePic?: string | null;
    gender?: string | null;
    userTypeId?: number | null;
    lname?: string | null;
    consultancyUserId?: number | null;
    consultancyUsers?: Array<ConsultancyUserDto> | null;
}

