/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConsultancyUserDtoForReturn } from './consultancy-user-dto-for-return';


export interface UserDto { 
    id?: number;
    fname?: string | null;
    userName?: string | null;
    email?: string | null;
    address?: string | null;
    cityId?: number | null;
    phone?: string | null;
    linkedin?: string | null;
    active?: boolean | null;
    profilePic?: string | null;
    updated?: string | null;
    alternateEmail?: string | null;
    password?: string | null;
    gender?: string | null;
    userTypeId?: number | null;
    otpemail?: string | null;
    emailVerified?: boolean | null;
    otpaltEmail?: string | null;
    altEmailVerified?: boolean | null;
    otpemailDate?: string | null;
    otpaltEmailDate?: string | null;
    resetPassword?: boolean | null;
    lname?: string | null;
    noOfViews?: number | null;
    noOfPosting?: number | null;
    updatedBy?: number | null;
    otppwdReset?: string | null;
    otppwdDateTime?: string | null;
    consultancyUserId?: number | null;
    roleRecruiter?: boolean | null;
    roleBenchSales?: boolean | null;
    consultancyUsers?: Array<ConsultancyUserDtoForReturn> | null;
}

