/**
 * REST API
 * Rest Calls
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDtoForInsert } from './user-dto-for-insert';


export interface UserDetailsDtoForInsert { 
    userDtoForInsert?: UserDtoForInsert;
    consultancyID?: number | null;
}

