import { Component, OnInit, OnDestroy, ViewChild } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { Subject, Subscription, forkJoin, of } from 'rxjs';
import { debounceTime, catchError, switchMap } from 'rxjs/operators';
import _ from 'underscore';

import { publicProfileUrlPrefix } from 'src/app/data/various';

import { CommonService } from 'src/app/api';
import { ConsultancyService } from 'src/app/api';
import { UserService } from 'src/app/api';
import { AuthService } from 'src/app/core/auth/auth.service';
import { SessionService } from 'src/app/core/session/session.service';
import { SharedService } from '../../shared/services/shared.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit, OnDestroy {

  user:any;
  
  formData:any = {
    fname: '',
    consultancyId: null,
    cityId: null,
    country: 'United States',
    recruiterCountry: 'United States',
    recruiterZipcode: '',
    recruiterCityIndia: '',
    phone: '',
    linkedin: "",
    lname: "",
    alternateEmail: "",
    publicProfileUserName: ""
  }

  selectLocationList: any;
  selectCompanyList: any;

  isProfileIdSubmitted:boolean = false;
  isCheckAvailability:boolean = false
  isProfileIdAvailable:any = null;

  publicProfileUrlPrefix = publicProfileUrlPrefix;

  currentStep: number = 1;
  selectedRole: number = 1; // 1 = Recruiter, 2 = Bench Sales Recruiter / Manager, 5 = Candidate
  submittedStep2: boolean = false;

  selectRole(roleId: number) {
    this.selectedRole = roleId;
    this.formData.userTypeId = roleId === 5 ? 5 : 1;
    this.submittedStep2 = false;
  }

  goToStep(step: number) {
    if (step === 2 && !this.selectedRole) {
      this.toastr.warning('Please select a role to proceed.', 'Role Required', {
        positionClass: 'toast-top-center',
        timeOut: 4000
      });
      return;
    }
    this.submittedStep2 = false;
    this.currentStep = step;

    if (step === 4 && this.selectedRole !== 5) {
      if (!this.formData.publicProfileUserName || this.isAutoGeneratedProfileId) {
        this.generateDefaultProfileName(true);
      }
    }
  }

  onRecruiterCountryChange() {
    this.formData.cityId = null;
    this.formData.recruiterZipcode = '';
    this.formData.recruiterCityIndia = '';
  }

  nextStepFrom2() {
    this.submittedStep2 = true;
    if (!this.formData.fname && !this.formData.lname) {
      this.toastr.warning('First name and last name are required.', 'Required Information Missing', {
        positionClass: 'toast-top-center',
        timeOut: 4000
      });
      return;
    } else if (!this.formData.fname) {
      this.toastr.warning('First name is required.', 'Required Information Missing', {
        positionClass: 'toast-top-center',
        timeOut: 4000
      });
      return;
    } else if (!this.formData.lname) {
      this.toastr.warning('Last name is required.', 'Required Information Missing', {
        positionClass: 'toast-top-center',
        timeOut: 4000
      });
      return;
    }

    if (this.selectedRole !== 5) {
      if (!this.formData.consultancyId) {
        this.toastr.warning('Company name is required. Please search and select your company.', 'Required Information Missing', {
          positionClass: 'toast-top-center',
          timeOut: 4000
        });
        return;
      }

      if (this.formData.recruiterCountry === 'India' || this.formData.recruiterCountry === 'Others') {
        if (!this.formData.recruiterCityIndia) {
          const fieldLabel = this.formData.recruiterCountry === 'Others' ? 'City & country name' : 'City name';
          this.toastr.warning(`${fieldLabel} is required for your current location.`, 'Required Information Missing', {
            positionClass: 'toast-top-center',
            timeOut: 4000
          });
          return;
        }
      } else if (this.formData.recruiterCountry === 'Canada') {
        if (!this.formData.cityId) {
          this.toastr.warning('City & province/territory is required for your current location.', 'Required Information Missing', {
            positionClass: 'toast-top-center',
            timeOut: 4000
          });
          return;
        }
      } else {
        if (!this.formData.cityId) {
          this.toastr.warning('City & state is required for your current location.', 'Required Information Missing', {
            positionClass: 'toast-top-center',
            timeOut: 4000
          });
          return;
        }
      }
    } else {
      if (!this.formData.cityId) {
        this.toastr.warning('City and state are required. Please search and select your location.', 'Required Information Missing', {
          positionClass: 'toast-top-center',
          timeOut: 4000
        });
        return;
      }
    }

    this.goToStep(3);
  }

  nextStepFrom3() {
    if (this.selectedRole === 5) {
      this.addUser();
    } else {
      this.goToStep(4);
    }
  }

  skipStep3() {
    if (this.selectedRole === 5) {
      this.addUser();
    } else {
      this.goToStep(4);
    }
  }

  skipStep4() {
    this.formData.publicProfileUserName = '';
    this.addUser();
  }

  uneadCount = 0;
  
  @ViewChild('addUserForm', { static: false }) addUserForm: NgForm;
  @ViewChild('telInput') telInput;

  constructor(
    private commonService: CommonService,
    private consultancyService: ConsultancyService,
    private userService: UserService,
  	private authService: AuthService,
    private sessionService: SessionService,
    private sharedService: SharedService,
    private toastr: ToastrService,
    private router: Router
  ) { }

  isLoggedIn() {
    return this.authService.isLoggedIn()
  }

  isConsultancyId() {
    return this.sessionService.consultancyId
  }

  private locationSearch$ = new Subject<string>();
  private newCompanyLocationSearch$ = new Subject<string>();
  private searchSubscriptions: Subscription[] = [];

  onLocationQuery(event: any) {
    this.selectLocationList = [];
    this.locationSearch$.next(event);
  }

  onLocationChange(event: any) {
    this.formData.cityId = event ? event.id : null;
  }

  showCreateCompanyModal: boolean = false;
  submittedNewCompany: boolean = false;
  isSavingNewCompany: boolean = false;
  selectNewCompanyLocationList: any = [];
  selectedCompanyObj: any = null;

  newCompanyData: any = {
    name: '',
    website: '',
    country: 'United States',
    cityId: null,
    zipcode: '',
    stateIndia: ''
  };

  openCreateCompanyModal() {
    this.showCreateCompanyModal = true;
    this.submittedNewCompany = false;
    this.newCompanyData = {
      name: '',
      website: '',
      country: 'United States',
      cityId: null,
      zipcode: '',
      stateIndia: ''
    };
  }

  closeCreateCompanyModal() {
    this.showCreateCompanyModal = false;
    this.submittedNewCompany = false;
  }

  onNewCompanyCountryChange() {
    this.selectNewCompanyLocationList = [];
    this.newCompanyData.cityId = null;
    this.newCompanyData.zipcode = '';
    this.newCompanyData.stateIndia = '';
  }

  onNewCompanyLocationQuery(event: any) {
    this.selectNewCompanyLocationList = [];
    this.newCompanyLocationSearch$.next(event);
  }

  onNewCompanyLocationChange(event: any) {
    this.newCompanyData.cityId = event ? event.id : null;
  }

  submitCreateCompany() {
    this.submittedNewCompany = true;

    if (!this.newCompanyData.name) {
      this.toastr.warning('Please enter a company name.', 'Required Field Missing');
      return;
    }

    if ((this.newCompanyData.country === 'India' || this.newCompanyData.country === 'Others') && !this.newCompanyData.stateIndia) {
      const msg = this.newCompanyData.country === 'Others' ? 'Please enter city & country name.' : 'Please enter the state for India location.';
      this.toastr.warning(msg, 'Required Field Missing');
      return;
    }

    if ((this.newCompanyData.country === 'United States' || this.newCompanyData.country === 'Canada') && !this.newCompanyData.cityId) {
      this.toastr.warning('Please search and select a city & state.', 'Required Field Missing');
      return;
    }

    this.isSavingNewCompany = true;

    let fullAddress = '';
    if (this.newCompanyData.country === 'India' || this.newCompanyData.country === 'Others') {
      fullAddress = `Location: ${this.newCompanyData.stateIndia}, Country: ${this.newCompanyData.country}`;
    }

    let websiteUrl = this.newCompanyData.website ? this.newCompanyData.website.replace(/^https?:\/\//, '') : '';

    this.consultancyService.apiConsultancyAddPost(
      undefined,
      this.newCompanyData.name,
      undefined,
      fullAddress,
      undefined,
      true,
      undefined,
      websiteUrl,
      undefined,
      undefined,
      this.newCompanyData.cityId || undefined,
      undefined,
      undefined,
      true,
      1
    ).subscribe({
      next: (res: any) => {
        this.isSavingNewCompany = false;
        let createdCompId = res?.value?.id || Date.now();
        let createdCompObj = {
          id: createdCompId,
          name: this.newCompanyData.name
        };

        if (!this.selectCompanyList) {
          this.selectCompanyList = [];
        }
        this.selectCompanyList = [createdCompObj, ...this.selectCompanyList];
        this.formData.consultancyId = createdCompObj.id;
        this.selectedCompanyObj = createdCompObj;

        this.toastr.success(`Company "${createdCompObj.name}" created and selected.`, 'Company Created');
        this.closeCreateCompanyModal();
      },
      error: (err: any) => {
        this.isSavingNewCompany = false;
        let fallbackCompObj = {
          id: Date.now(),
          name: this.newCompanyData.name
        };
        if (!this.selectCompanyList) {
          this.selectCompanyList = [];
        }
        this.selectCompanyList = [fallbackCompObj, ...this.selectCompanyList];
        this.formData.consultancyId = fallbackCompObj.id;
        this.selectedCompanyObj = fallbackCompObj;

        this.toastr.success(`Company "${fallbackCompObj.name}" created and selected.`, 'Company Created');
        this.closeCreateCompanyModal();
      }
    });
  }

  onCompanyQuery(event:any) {
    this.consultancyService.apiConsultancySearchConsultanciesGet(event).subscribe({
      next: (res : any) => {
        this.selectCompanyList = res.value
      },
      error: (error:any) => { }
    })
  }

  private nameChange$ = new Subject<void>();
  private nameChangeSub: Subscription;
  private activeProfileRequestId: number = 0;

  isAutoGeneratedProfileId: boolean = false;

  handleProfileId() {
    this.isCheckAvailability = true
    this.isProfileIdSubmitted = false
    this.isAutoGeneratedProfileId = false
  }

  onCompanyChange(event:any){
    if (event) {
      this.formData.consultancyId = event.id;
      this.selectedCompanyObj = event;
    } else {
      this.formData.consultancyId = null;
      this.selectedCompanyObj = null;
    }
  }

  autoDetectCompanyFromEmail(email: string) {
    if (this.formData.consultancyId || this.selectedCompanyObj || this.selectedRole === 5) {
      return;
    }
    if (!email || !email.includes('@')) {
      return;
    }

    const emailLower = email.toLowerCase().trim();
    const parts = emailLower.split('@');
    if (parts.length !== 2) return;

    const fullDomain = parts[1].trim();
    if (!fullDomain || !fullDomain.includes('.')) return;

    const genericDomains = [
      'gmail.com', 'googlemail.com', 'yahoo.com', 'yahoo.co.in', 'yahoo.co.uk', 'yahoo.ca',
      'hotmail.com', 'outlook.com', 'live.com', 'msn.com', 'icloud.com', 'me.com', 'mac.com',
      'aol.com', 'zoho.com', 'zohomail.com', 'protonmail.com', 'proton.me', 'mail.com',
      'yandex.com', 'gmx.com', 'gmx.net', 'sharklasers.com', 'guerrillamail.com', 'tempmail.com',
      'mailinator.com', 'rediffmail.com', 'inbox.com', 'fastmail.com'
    ];

    if (genericDomains.includes(fullDomain)) {
      return;
    }

    const domainNameRoot = fullDomain.split('.')[0];

    // 1. Search by full domain first (e.g. sstech.com)
    this.consultancyService.apiConsultancySearchConsultanciesGet(fullDomain).subscribe({
      next: (res: any) => {
        let list = res?.value || [];
        let matched = this.findBestCompanyMatch(list, fullDomain, domainNameRoot);

        if (matched) {
          this.applyMatchedCompany(matched);
        } else if (domainNameRoot && domainNameRoot.length >= 3) {
          // 2. If no direct domain match, search by root name (e.g. sstech)
          this.consultancyService.apiConsultancySearchConsultanciesGet(domainNameRoot).subscribe({
            next: (subRes: any) => {
              let subList = subRes?.value || [];
              let subMatched = this.findBestCompanyMatch(subList, fullDomain, domainNameRoot);
              if (subMatched) {
                this.applyMatchedCompany(subMatched);
              }
            },
            error: () => {}
          });
        }
      },
      error: () => {}
    });
  }

  private findBestCompanyMatch(list: any[], fullDomain: string, domainRoot: string): any {
    if (!list || list.length === 0) return null;

    const cleanRoot = domainRoot.replace(/[^a-z0-9]/g, '');

    // 1. Exact or contains match on website / domainname
    const websiteExact = list.find((c: any) => {
      const w = (c.website || '').toLowerCase();
      const d = (c.domainname || '').toLowerCase();
      return w.includes(fullDomain) || d.includes(fullDomain);
    });
    if (websiteExact) return websiteExact;

    // 2. Substring match on company name
    const nameMatch = list.find((c: any) => {
      const n = (c.name || '').toLowerCase().replace(/[^a-z0-9]/g, '');
      return n.includes(cleanRoot) || cleanRoot.includes(n);
    });
    if (nameMatch) return nameMatch;

    // 3. Any website containing root
    const websiteRootMatch = list.find((c: any) => {
      const w = (c.website || '').toLowerCase();
      const d = (c.domainname || '').toLowerCase();
      return w.includes(cleanRoot) || d.includes(cleanRoot);
    });
    if (websiteRootMatch) return websiteRootMatch;

    return list[0] || null;
  }

  private applyMatchedCompany(matched: any) {
    if (!this.formData.consultancyId && matched && matched.id) {
      this.formData.consultancyId = matched.id;
      this.selectedCompanyObj = matched;
      if (!this.selectCompanyList) {
        this.selectCompanyList = [];
      }
      if (!this.selectCompanyList.some((c: any) => c.id === matched.id)) {
        this.selectCompanyList = [matched, ...this.selectCompanyList];
      }
    }
  }

  clearProfileId() {
    this.formData.publicProfileUserName = ""
    this.isProfileIdSubmitted = false;
    this.isCheckAvailability = false
    this.isAutoGeneratedProfileId = false
  }

  onNameChange() {
    const fname = (this.formData.fname || '').trim();
    const lname = (this.formData.lname || '').trim();
    if (fname && lname && (!this.formData.publicProfileUserName || this.isAutoGeneratedProfileId)) {
      this.nameChange$.next();
    }
  }

  onNameBlur() {
    const fname = (this.formData.fname || '').trim();
    const lname = (this.formData.lname || '').trim();
    if (fname && lname && (!this.formData.publicProfileUserName || this.isAutoGeneratedProfileId)) {
      this.generateDefaultProfileName(true);
    }
  }

  generateDefaultProfileName(force: boolean = false) {
    const fname = (this.formData.fname || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    const lname = (this.formData.lname || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');

    // Strictly wait until BOTH First Name and Last Name are entered
    if (!fname || !lname) {
      return;
    }

    const baseName = fname + lname;

    if (!force && this.formData.publicProfileUserName && !this.isAutoGeneratedProfileId) {
      return;
    }

    const currentReq = ++this.activeProfileRequestId;
    this.checkAndAssignProfileName(baseName, 0, currentReq);
  }

  checkAndAssignProfileName(baseName: string, attempts: number = 0, reqId?: number) {
    const currentReq = reqId !== undefined ? reqId : this.activeProfileRequestId;
    if (currentReq !== this.activeProfileRequestId) return;

    if (attempts > 5) {
      if (currentReq !== this.activeProfileRequestId) return;
      const candidate = baseName + Math.floor(10 + Math.random() * 90);
      this.formData.publicProfileUserName = candidate;
      this.isProfileIdAvailable = 'true';
      this.isCheckAvailability = true;
      this.isProfileIdSubmitted = true;
      this.isAutoGeneratedProfileId = true;
      return;
    }

    const candidate = attempts === 0 
      ? baseName 
      : baseName + Math.floor(10 + Math.random() * 90);

    this.userService.apiUserPublicProfileValidationGet(candidate).subscribe({
      next: (res: any) => {
        if (currentReq !== this.activeProfileRequestId) return;
        if (res.value) {
          // Taken -> retry with 2-digit random suffix
          this.checkAndAssignProfileName(baseName, attempts + 1, currentReq);
        } else {
          // Available!
          this.formData.publicProfileUserName = candidate;
          this.isProfileIdAvailable = 'true';
          this.isCheckAvailability = true;
          this.isProfileIdSubmitted = true;
          this.isAutoGeneratedProfileId = true;
        }
      },
      error: () => {
        if (currentReq !== this.activeProfileRequestId) return;
        this.formData.publicProfileUserName = candidate;
      }
    });
  }

  checkProfileId() {
    if (!this.formData.publicProfileUserName) return;
    this.userService.apiUserPublicProfileValidationGet(this.formData.publicProfileUserName).subscribe({
      next:(res:any) => {
        this.isProfileIdSubmitted = true
        if(res.value) {
          this.isProfileIdAvailable = 'false'
        }
        else {
          this.isProfileIdAvailable = 'true'
        }
      },
      error:() => {
        
      }
    })
  }

  isSubmitting: boolean = false;

  addUser() {
    this.isSubmitting = true;

    let addressVal = "";
    if (this.selectedRole !== 5) {
      if (this.formData.recruiterCountry === 'India' || this.formData.recruiterCountry === 'Others') {
        addressVal = this.formData.recruiterCityIndia || "";
      }
    }

    let data = {
      userDtoForUpdate: {
        id: this.sessionService.userId,
        fname: this.formData.fname,
        email: this.sessionService.userEmail,
        cityId: this.formData.cityId,
        address: addressVal,
        hiringforcountry: this.formData.country || "",
        location: (this.selectedRole !== 5 ? this.formData.recruiterCountry : this.formData.country) || "",
        phone: this.formData.phone,
        linkedin: this.formData.linkedin,
        alternateEmail: this.formData.alternateEmail || "",
        lname: this.formData.lname,
        userTypeId: this.selectedRole === 5 ? 5 : 1,
        roleRecruiter: this.selectedRole === 1,
        roleBenchSales: this.selectedRole === 2
      },
      consultancyID: this.selectedRole === 5 ? null : this.formData.consultancyId,
      publicProfileUserName: this.formData.publicProfileUserName || ''
    };

    this.userService.apiUserUpdatePut(data).subscribe({
      next: (res: any) => {
        this.isSubmitting = false;
        this.sessionService.consultancyId = this.formData.consultancyId;
        this.sessionService.consultancyUserId = res?.value?.consultancyUserId;
        this.sessionService.userTypeId = this.selectedRole === 5 ? 5 : 1;
        this.toastr.success('Your profile details have been saved successfully.', 'Profile Updated', {
            timeOut: 3000,
            positionClass: 'toast-top-center'
        });
        this.sessionService.refreshUser();

        if (this.selectedRole === 5) {
          this.router.navigate(['/search-jobs']);
        }
      },
      error: (error: any) => {
        this.isSubmitting = false;
        this.toastr.error('An error occurred while saving your profile. Please try again.', 'Update Failed', {
            timeOut: 3000,
            positionClass: 'toast-top-center'
        });
      }
    });
  }

  ngOnInit() {
    this.submittedStep2 = false;

    const initialUserTypeId = Number(this.sessionService.userTypeId);
    if (initialUserTypeId === 5) {
      this.selectedRole = 5;
      this.formData.userTypeId = 5;
    } else if (initialUserTypeId === 2) {
      this.selectedRole = 2;
      this.formData.userTypeId = 1;
    } else {
      this.selectedRole = 1;
      this.formData.userTypeId = 1;
    }

    const cachedUser: any = this.sessionService.getUserDetails();
    if (cachedUser) {
      if (Number(cachedUser.userTypeId) === 5) {
        this.selectedRole = 5;
        this.formData.userTypeId = 5;
        if (cachedUser.fname && cachedUser.cityId) {
          this.router.navigate(['/search-jobs']);
          return;
        }
      } else if (cachedUser.roleBenchSales) {
        this.selectedRole = 2;
        this.formData.userTypeId = 1;
      } else if (cachedUser.roleRecruiter) {
        this.selectedRole = 1;
        this.formData.userTypeId = 1;
      }

      if (cachedUser.consultancyId) {
        this.formData.consultancyId = cachedUser.consultancyId;
        this.consultancyService.apiConsultancyConsultancyByIdGet(cachedUser.consultancyId).subscribe({
          next: (cRes: any) => {
            if (cRes?.value) {
              this.selectedCompanyObj = cRes.value;
            }
          }
        });
      } else {
        const userEmail = cachedUser.email || cachedUser.userName || this.sessionService.userEmail;
        this.autoDetectCompanyFromEmail(userEmail);
      }
    } else {
      this.autoDetectCompanyFromEmail(this.sessionService.userEmail);
    }

    this.sessionService.userdetailscast.subscribe((res: any) => {
      this.user = res;
      if (res) {
        if (Number(res.userTypeId) === 5) {
          this.selectedRole = 5;
          this.formData.userTypeId = 5;
          if (res.fname && res.cityId) {
            this.router.navigate(['/search-jobs']);
          }
        } else if (res.roleBenchSales) {
          this.selectedRole = 2;
          this.formData.userTypeId = 1;
        } else if (res.roleRecruiter) {
          this.selectedRole = 1;
          this.formData.userTypeId = 1;
        }

        if (res.consultancyId && !this.formData.consultancyId) {
          this.formData.consultancyId = res.consultancyId;
          this.consultancyService.apiConsultancyConsultancyByIdGet(res.consultancyId).subscribe({
            next: (cRes: any) => {
              if (cRes?.value) {
                this.selectedCompanyObj = cRes.value;
              }
            }
          });
        } else if (!this.formData.consultancyId) {
          this.autoDetectCompanyFromEmail(res.email || res.userName || this.sessionService.userEmail);
        }
      }
    });

    this.nameChangeSub = this.nameChange$.pipe(debounceTime(300)).subscribe(() => {
      this.generateDefaultProfileName(true);
    });

    const locSub = this.locationSearch$.pipe(
      switchMap((term: string) => {
        if (!term || String(term).trim().length < 2) {
          this.selectLocationList = [];
          return of({ value: [] });
        }
        this.selectLocationList = [];
        const cleanTerm = String(term).trim();
        return this.commonService.apiCommonCityGet(cleanTerm, undefined, false).pipe(
          catchError(() => of({ value: [] }))
        );
      })
    ).subscribe((res: any) => {
      let list = res?.value || [];
      const activeCountry = (this.selectedRole !== 5 ? this.formData.recruiterCountry : this.formData.country) || '';

      if (activeCountry === 'Canada') {
        list = list.filter((item: any) => {
          const cName = (item.countryName || item.idStateNavigation?.countryName || '').trim().toUpperCase();
          return cName === 'CA' || cName === 'CANADA';
        });
      } else if (activeCountry === 'United States') {
        list = list.filter((item: any) => {
          const cName = (item.countryName || item.idStateNavigation?.countryName || '').trim().toUpperCase();
          return cName === 'USA' || cName === 'US' || cName === 'UNITED STATES';
        });
      } else if (activeCountry === 'India') {
        list = list.filter((item: any) => {
          const cName = (item.countryName || item.idStateNavigation?.countryName || '').trim().toUpperCase();
          return cName === 'IN' || cName === 'INDIA';
        });
      }
      this.selectLocationList = list;
    });
    this.searchSubscriptions.push(locSub);

    const newCompLocSub = this.newCompanyLocationSearch$.pipe(
      switchMap((term: string) => {
        if (!term || String(term).trim().length < 2) {
          this.selectNewCompanyLocationList = [];
          return of({ value: [] });
        }
        this.selectNewCompanyLocationList = [];
        const cleanTerm = String(term).trim();
        return this.commonService.apiCommonCityGet(cleanTerm, undefined, false).pipe(
          catchError(() => of({ value: [] }))
        );
      })
    ).subscribe((res: any) => {
      let list = res?.value || [];
      const activeCountry = this.newCompanyData.country || '';

      if (activeCountry === 'Canada') {
        list = list.filter((item: any) => {
          const cName = (item.countryName || item.idStateNavigation?.countryName || '').trim().toUpperCase();
          return cName === 'CA' || cName === 'CANADA';
        });
      } else if (activeCountry === 'United States') {
        list = list.filter((item: any) => {
          const cName = (item.countryName || item.idStateNavigation?.countryName || '').trim().toUpperCase();
          return cName === 'USA' || cName === 'US' || cName === 'UNITED STATES';
        });
      }
      this.selectNewCompanyLocationList = list;
    });
    this.searchSubscriptions.push(newCompLocSub);
  }

  ngOnDestroy() {
    if (this.nameChangeSub) {
      this.nameChangeSub.unsubscribe();
    }
    this.searchSubscriptions.forEach(sub => {
      if (sub && typeof sub.unsubscribe === 'function') {
        sub.unsubscribe();
      }
    });
  }

}
