import { Component, ViewChild } from '@angular/core';
import { UserService } from 'src/app/api';
import { UserDetailsDtoForUpdate } from 'src/app/api';
import { SessionService } from 'src/app/core/session/session.service';
import { AuthService } from 'src/app/core/auth/auth.service';
import { SharedService } from 'src/app/modules/shared/services/shared.service';
import { ConsultancyService } from 'src/app/api';
import { ToastrService } from 'ngx-toastr';
import { publicProfileUrlPrefix } from 'src/app/data/various';
import _ from 'underscore';

@Component({
  selector: 'personal-details',
  templateUrl: './personal-details.component.html',
  styleUrls: ['./personal-details.component.scss']
})
export class PersonalDetailsComponent {


isLoaded:boolean = false;
isError:boolean = false;
error = '';
successMessage: string = '';
errorMessage: string = '';

userData: UserDetailsDtoForUpdate = {};
formData: any;
companyData:any = {};
userPhone = '';
userTypeId;

isEdit:boolean = false;

selectCompanyList: any;

publicProfileUrlPrefix = publicProfileUrlPrefix;

isProfileIdSubmitted:boolean = false
isCheckAvailability:boolean = false
isProfileIdAvailable:any = null;

initialProfileId = ""

isFormSubmitted:boolean = false;

  @ViewChild('myProfileForm') myProfileForm:any;
  @ViewChild('telInput') telInput;

  constructor(
    private userService: UserService,
    private consultancyService: ConsultancyService,
    private authService: AuthService,
    private sessionService: SessionService,
    private sharedService: SharedService,
    private toastr: ToastrService
  ) {

  }

  isAutoGeneratedProfileId: boolean = false;

  checkProfileId() {
    if (!this.formData.publicProfileUserName) return;
    this.userService.apiUserPublicProfileValidationGet(this.formData.publicProfileUserName).subscribe({
      next:(res:any) => {
        this.isProfileIdSubmitted = true
        if(res.value) {
          this.isProfileIdAvailable = 'false'
        }
        else {
          this.isProfileIdAvailable = 'true'
        }
      },
      error:() => {
        
      }
    })
  }

  clearProfileId() {
    this.formData.publicProfileUserName = this.initialProfileId
    this.isAutoGeneratedProfileId = false;
  }

  handleProfileId() {
    this.isCheckAvailability = true
    this.isProfileIdSubmitted = false
    this.isAutoGeneratedProfileId = false
  }

  onNameChange() {
    if (!this.formData.publicProfileUserName || this.isAutoGeneratedProfileId) {
      this.generateDefaultProfileName(true);
    }
  }

  generateDefaultProfileName(force: boolean = false) {
    const fname = (this.formData.fname || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    const lname = (this.formData.lname || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    const baseName = fname + lname;

    if (!baseName) return;

    if (!force && this.formData.publicProfileUserName && !this.isAutoGeneratedProfileId) {
      return;
    }

    this.checkAndAssignProfileName(baseName, 0);
  }

  checkAndAssignProfileName(baseName: string, attempts: number = 0) {
    if (attempts > 5) {
      const candidate = baseName + Math.floor(10 + Math.random() * 90);
      this.formData.publicProfileUserName = candidate;
      this.isProfileIdAvailable = 'true';
      this.isCheckAvailability = true;
      this.isProfileIdSubmitted = true;
      this.isAutoGeneratedProfileId = true;
      return;
    }

    const candidate = attempts === 0 
      ? baseName 
      : baseName + Math.floor(10 + Math.random() * 90);

    this.userService.apiUserPublicProfileValidationGet(candidate).subscribe({
      next: (res: any) => {
        if (res.value) {
          // Taken -> retry with 2-digit random suffix
          this.checkAndAssignProfileName(baseName, attempts + 1);
        } else {
          // Available!
          this.formData.publicProfileUserName = candidate;
          this.isProfileIdAvailable = 'true';
          this.isCheckAvailability = true;
          this.isProfileIdSubmitted = true;
          this.isAutoGeneratedProfileId = true;
        }
      },
      error: () => {
        this.formData.publicProfileUserName = candidate;
      }
    });
  }

  onCompanyQuery(event:any) {
    this.consultancyService.apiConsultancySearchConsultanciesGet(event).subscribe({
      next: (res : any) => {
        this.selectCompanyList = res.value
      },
      error: (error:any) => { }
    })
  }

  onCompanyChange(event:any){
    this.userData.consultancyID = event.id
  }

  onJobRoleChange() {
    const roleVal = parseInt(this.userTypeId);
    this.formData.roleRecruiter = (roleVal === 1 || roleVal === 3);
    this.formData.roleBenchSales = (roleVal === 2 || roleVal === 3);
    this.formData.userTypeId = (roleVal === 5 ? 5 : 1);
  }

  scrollToTop() {
    window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
    const el = document.querySelector('.personal-details-wrapper') || document.querySelector('.my-account-page');
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }

  handleCancel() {
    this.isEdit = false;
    this.successMessage = '';
    this.errorMessage = '';
    if(this.myProfileForm.dirty) {
      this.reFetchData();
    }
  }

  refreshUser() {

    let user = {
      userEmail : this.formData.email,
      userId: this.sessionService.userId,
      token: this.authService.token,
      userTypeId: this.formData.userTypeId,
      consultancyId: this.userData.consultancyID,
      consultancyUserId: this.sessionService.consultancyUserId
    }
    this.authService.login(user)

  }

  submitMyProfileForm() {

    this.isFormSubmitted = true
    this.successMessage = '';
    this.errorMessage = '';

    for (const field in this.myProfileForm.controls) {
      if (this.myProfileForm.controls.hasOwnProperty(field)) {
        const control = this.myProfileForm.controls[field];
        if (control.invalid) {
          console.log(`Invalid field: ${field}`);
        }
      }
    }


    if (!this.myProfileForm.valid) {
      this.scrollToTop()
      this.isFormSubmitted = false
    }
    else {
      
      if(!this.isProfileIdSubmitted) {
        this.formData.publicProfileUserName = this.initialProfileId
      }

      const roleVal = parseInt(this.userTypeId);
      this.formData.roleRecruiter = (roleVal === 1 || roleVal === 3);
      this.formData.roleBenchSales = (roleVal === 2 || roleVal === 3);
      this.formData.userTypeId = (roleVal === 5 ? 5 : 1);

      this.formData.updated = new Date().toISOString()
      this.formData.phone = this.userPhone
      this.userData.publicProfileUserName = this.formData.publicProfileUserName

      const { ['publicProfileUserName']: _, ...tempObject } = this.formData;
      this.userData.userDtoForUpdate = tempObject
      
      this.userService.apiUserUpdatePut(this.userData).subscribe({
        next:(res:any) => {
          this.isEdit = false;
          this.successMessage = 'Personal details updated successfully.';
          this.toastr.success('Personal details updated successfully', '', {
            timeOut: 3000,
            positionClass: 'toast-top-center'
          });
          this.scrollToTop();
          this.sharedService.setUserUpdate(true);
          this.refreshUser();
          this.reFetchData();
          this.isFormSubmitted = false;

          setTimeout(() => {
            this.successMessage = '';
          }, 6000);
        },
        error:(error:any) => {
          this.isFormSubmitted = false;
          this.errorMessage = error?.error?.message || 'Failed to update personal details. Please try again.';
          this.toastr.error(this.errorMessage, 'Error');
          this.scrollToTop();
        },
      })

    }

  }

  reFetchData() {

    this.userService.apiUserGetUserByUserNameGet(this.sessionService.userEmail).subscribe({
      next:(res:any) => {
        
        this.formData = res.value[0]
        this.userPhone = this.formData.phone ? this.formData.phone : '';
        if (this.formData.roleRecruiter && this.formData.roleBenchSales) {
          this.userTypeId = '3';
        } else if (this.formData.roleBenchSales) {
          this.userTypeId = '2';
        } else if (this.formData.roleRecruiter) {
          this.userTypeId = '1';
        } else {
          this.userTypeId = this.formData.userTypeId?.toString();
        }
        
      },
      error:(error:any) => {
 
      }
    })

  }

  ngOnInit() {

    this.userService.apiUserGetUserByUserNameGet(this.sessionService.userEmail).subscribe({
      next:(res:any) => {
        
        this.formData = res.value[0]
        const existingProfileId = res.value[0]?.consultancyUsers?.[0]?.publicProfileUserName
        if (existingProfileId && existingProfileId.trim() !== '') {
          this.initialProfileId = existingProfileId
          this.formData.publicProfileUserName = existingProfileId
        } else {
          this.generateDefaultProfileName(true)
        }
        
        this.userPhone = this.formData.phone ? this.formData.phone : '';
        if (this.formData.roleRecruiter && this.formData.roleBenchSales) {
          this.userTypeId = '3';
        } else if (this.formData.roleBenchSales) {
          this.userTypeId = '2';
        } else if (this.formData.roleRecruiter) {
          this.userTypeId = '1';
        } else {
          this.userTypeId = this.formData.userTypeId?.toString();
        }
        console.log(this.formData)
        this.isLoaded = true
        this.isError = false
        

      },
      error:(error:any) => {
        console.log(error)
        this.isLoaded = true
        this.isError = true
        this.error = 'Some error occured'
      }
    })

    this.consultancyService.apiConsultancyConsultancyByIdGet(this.sessionService.consultancyId).subscribe({
      next: (res:any) => {
        this.companyData = res.value;
      },
      error: (error:any) => {
        console.log(error);
      }
    })

  }

}
