import { Component, OnInit, OnDestroy, ViewChild } from '@angular/core';
import { Subject, Subscription } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { UserService } from 'src/app/api';
import { UserDetailsDtoForUpdate } from 'src/app/api';
import { SessionService } from 'src/app/core/session/session.service';
import { AuthService } from 'src/app/core/auth/auth.service';
import { SharedService } from 'src/app/modules/shared/services/shared.service';
import { ConsultancyService } from 'src/app/api';
import { ToastrService } from 'ngx-toastr';
import { publicProfileUrlPrefix } from 'src/app/data/various';
import { getMeaningfulErrorMessage } from 'src/app/modules/shared/utils/error-handler.util';
import _ from 'underscore';

@Component({
  selector: 'personal-details',
  templateUrl: './personal-details.component.html',
  styleUrls: ['./personal-details.component.scss']
})
export class PersonalDetailsComponent implements OnInit, OnDestroy {


isLoaded:boolean = false;
isError:boolean = false;
error = '';
successMessage: string = '';
errorMessage: string = '';

userData: UserDetailsDtoForUpdate = {};
formData: any;
companyData:any = {};
userPhone = '';
userTypeId;

isEdit:boolean = false;

selectCompanyList: any;

publicProfileUrlPrefix = publicProfileUrlPrefix;

isProfileIdSubmitted:boolean = false
isCheckAvailability:boolean = false
isProfileIdAvailable:any = null;

initialProfileId = ""

isFormSubmitted:boolean = false;

  @ViewChild('myProfileForm') myProfileForm:any;
  @ViewChild('telInput') telInput;

  constructor(
    private userService: UserService,
    private consultancyService: ConsultancyService,
    private authService: AuthService,
    private sessionService: SessionService,
    private sharedService: SharedService,
    private toastr: ToastrService
  ) {

  }

  isAutoGeneratedProfileId: boolean = false;

  checkProfileId() {
    if (!this.formData.publicProfileUserName) return;
    this.userService.apiUserPublicProfileValidationGet(this.formData.publicProfileUserName).subscribe({
      next:(res:any) => {
        this.isProfileIdSubmitted = true
        if(res.value) {
          this.isProfileIdAvailable = 'false'
        }
        else {
          this.isProfileIdAvailable = 'true'
        }
      },
      error:() => {
        
      }
    })
  }

  clearProfileId() {
    this.formData.publicProfileUserName = this.initialProfileId
    this.isAutoGeneratedProfileId = false;
  }

  private nameChange$ = new Subject<void>();
  private nameChangeSub: Subscription;
  private activeProfileRequestId: number = 0;

  handleProfileId() {
    this.isCheckAvailability = true
    this.isProfileIdSubmitted = false
    this.isAutoGeneratedProfileId = false
  }

  onNameChange() {
    const fname = (this.formData?.fname || '').trim();
    const lname = (this.formData?.lname || '').trim();
    if (fname && lname && (!this.formData?.publicProfileUserName || this.isAutoGeneratedProfileId)) {
      this.nameChange$.next();
    }
  }

  onNameBlur() {
    const fname = (this.formData?.fname || '').trim();
    const lname = (this.formData?.lname || '').trim();
    if (fname && lname && (!this.formData?.publicProfileUserName || this.isAutoGeneratedProfileId)) {
      this.generateDefaultProfileName(true);
    }
  }

  generateDefaultProfileName(force: boolean = false) {
    const fname = (this.formData?.fname || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');
    const lname = (this.formData?.lname || '').trim().toLowerCase().replace(/[^a-z0-9]/g, '');

    // Strictly wait until BOTH First Name and Last Name are entered
    if (!fname || !lname) {
      return;
    }

    const baseName = fname + lname;

    if (!force && this.formData?.publicProfileUserName && !this.isAutoGeneratedProfileId) {
      return;
    }

    const currentReq = ++this.activeProfileRequestId;
    this.checkAndAssignProfileName(baseName, 0, currentReq);
  }

  checkAndAssignProfileName(baseName: string, attempts: number = 0, reqId?: number) {
    const currentReq = reqId !== undefined ? reqId : this.activeProfileRequestId;
    if (currentReq !== this.activeProfileRequestId) return;

    if (attempts > 5) {
      if (currentReq !== this.activeProfileRequestId) return;
      const candidate = baseName + Math.floor(10 + Math.random() * 90);
      this.formData.publicProfileUserName = candidate;
      this.isProfileIdAvailable = 'true';
      this.isCheckAvailability = true;
      this.isProfileIdSubmitted = true;
      this.isAutoGeneratedProfileId = true;
      return;
    }

    const candidate = attempts === 0 
      ? baseName 
      : baseName + Math.floor(10 + Math.random() * 90);

    this.userService.apiUserPublicProfileValidationGet(candidate).subscribe({
      next: (res: any) => {
        if (currentReq !== this.activeProfileRequestId) return;
        if (res.value) {
          // Taken -> retry with 2-digit random suffix
          this.checkAndAssignProfileName(baseName, attempts + 1, currentReq);
        } else {
          // Available!
          this.formData.publicProfileUserName = candidate;
          this.isProfileIdAvailable = 'true';
          this.isCheckAvailability = true;
          this.isProfileIdSubmitted = true;
          this.isAutoGeneratedProfileId = true;
        }
      },
      error: () => {
        if (currentReq !== this.activeProfileRequestId) return;
        this.formData.publicProfileUserName = candidate;
      }
    });
  }

  onCompanyQuery(event:any) {
    this.consultancyService.apiConsultancySearchConsultanciesGet(event).subscribe({
      next: (res : any) => {
        this.selectCompanyList = res.value
      },
      error: (error:any) => { }
    })
  }

  onCompanyChange(event:any){
    if (event) {
      this.userData.consultancyID = event.id;
      this.companyData = event;
      this.companyData.website = this.companyData.website || this.companyData.Website || '';
    } else {
      this.userData.consultancyID = null;
      this.companyData = {};
    }
  }

  autoDetectCompanyFromEmail(email: string) {
    if (this.userData.consultancyID || this.companyData?.id || this.userTypeId === '5') {
      return;
    }
    if (!email || !email.includes('@')) {
      return;
    }

    const emailLower = email.toLowerCase().trim();
    const parts = emailLower.split('@');
    if (parts.length !== 2) return;

    const fullDomain = parts[1].trim();
    if (!fullDomain || !fullDomain.includes('.')) return;

    const genericDomains = [
      'gmail.com', 'googlemail.com', 'yahoo.com', 'yahoo.co.in', 'yahoo.co.uk', 'yahoo.ca',
      'hotmail.com', 'outlook.com', 'live.com', 'msn.com', 'icloud.com', 'me.com', 'mac.com',
      'aol.com', 'zoho.com', 'zohomail.com', 'protonmail.com', 'proton.me', 'mail.com',
      'yandex.com', 'gmx.com', 'gmx.net', 'sharklasers.com', 'guerrillamail.com', 'tempmail.com',
      'mailinator.com', 'rediffmail.com', 'inbox.com', 'fastmail.com'
    ];

    if (genericDomains.includes(fullDomain)) {
      return;
    }

    const domainNameRoot = fullDomain.split('.')[0];

    this.consultancyService.apiConsultancySearchConsultanciesGet(fullDomain).subscribe({
      next: (res: any) => {
        let list = res?.value || [];
        let matched = this.findBestCompanyMatch(list, fullDomain, domainNameRoot);

        if (matched) {
          this.applyMatchedCompany(matched);
        } else if (domainNameRoot && domainNameRoot.length >= 3) {
          this.consultancyService.apiConsultancySearchConsultanciesGet(domainNameRoot).subscribe({
            next: (subRes: any) => {
              let subList = subRes?.value || [];
              let subMatched = this.findBestCompanyMatch(subList, fullDomain, domainNameRoot);
              if (subMatched) {
                this.applyMatchedCompany(subMatched);
              }
            },
            error: () => {}
          });
        }
      },
      error: () => {}
    });
  }

  private findBestCompanyMatch(list: any[], fullDomain: string, domainRoot: string): any {
    if (!list || list.length === 0) return null;

    const cleanRoot = domainRoot.replace(/[^a-z0-9]/g, '');

    const websiteExact = list.find((c: any) => {
      const w = (c.website || '').toLowerCase();
      const d = (c.domainname || '').toLowerCase();
      return w.includes(fullDomain) || d.includes(fullDomain);
    });
    if (websiteExact) return websiteExact;

    const nameMatch = list.find((c: any) => {
      const n = (c.name || '').toLowerCase().replace(/[^a-z0-9]/g, '');
      return n.includes(cleanRoot) || cleanRoot.includes(n);
    });
    if (nameMatch) return nameMatch;

    const websiteRootMatch = list.find((c: any) => {
      const w = (c.website || '').toLowerCase();
      const d = (c.domainname || '').toLowerCase();
      return w.includes(cleanRoot) || d.includes(cleanRoot);
    });
    if (websiteRootMatch) return websiteRootMatch;

    return list[0] || null;
  }

  private applyMatchedCompany(matched: any) {
    if (!this.userData.consultancyID && matched && matched.id) {
      this.userData.consultancyID = matched.id;
      this.companyData = { ...matched };
      this.companyData.website = this.companyData.website || this.companyData.Website || '';
      if (!this.selectCompanyList) {
        this.selectCompanyList = [];
      }
      if (!this.selectCompanyList.some((c: any) => c.id === matched.id)) {
        this.selectCompanyList = [matched, ...this.selectCompanyList];
      }
    }
  }

  onJobRoleChange() {
    const roleVal = parseInt(this.userTypeId);
    this.formData.roleRecruiter = (roleVal === 1 || roleVal === 3);
    this.formData.roleBenchSales = (roleVal === 2 || roleVal === 3);
    this.formData.userTypeId = (roleVal === 5 ? 5 : 1);
  }

  scrollToTop() {
    window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
    const el = document.querySelector('.personal-details-wrapper') || document.querySelector('.my-account-page');
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }

  handleCancel() {
    this.isEdit = false;
    this.successMessage = '';
    this.errorMessage = '';
    if(this.myProfileForm.dirty) {
      this.reFetchData();
    }
  }

  refreshUser() {

    let user = {
      userEmail : this.formData.email,
      userId: this.sessionService.userId,
      token: this.authService.token,
      userTypeId: this.formData.userTypeId,
      consultancyId: this.userData.consultancyID,
      consultancyUserId: this.sessionService.consultancyUserId
    }
    this.authService.login(user)

  }

  submitMyProfileForm() {

    this.isFormSubmitted = true
    this.successMessage = '';
    this.errorMessage = '';

    for (const field in this.myProfileForm.controls) {
      if (this.myProfileForm.controls.hasOwnProperty(field)) {
        const control = this.myProfileForm.controls[field];
        if (control.invalid) {
          console.log(`Invalid field: ${field}`);
        }
      }
    }


    if (!this.myProfileForm.valid) {
      this.scrollToTop()
      this.isFormSubmitted = false
    }
    else {
      
      if(!this.isProfileIdSubmitted) {
        this.formData.publicProfileUserName = this.initialProfileId
      }

      const originalUserTypeId = Number(this.formData.userTypeId) || Number(this.sessionService.userTypeId);
      if (originalUserTypeId === 7) {
        this.formData.userTypeId = 7;
      } else {
        const roleVal = parseInt(this.userTypeId);
        this.formData.roleRecruiter = (roleVal === 1 || roleVal === 3);
        this.formData.roleBenchSales = (roleVal === 2 || roleVal === 3);
        this.formData.userTypeId = (roleVal === 5 ? 5 : 1);
      }

      this.formData.updated = new Date().toISOString()
      this.formData.phone = this.userPhone
      this.userData.publicProfileUserName = this.formData.publicProfileUserName

      const { ['publicProfileUserName']: _, ...tempObject } = this.formData;
      this.userData.userDtoForUpdate = tempObject
      
      this.userService.apiUserUpdatePut(this.userData).subscribe({
        next:(res:any) => {
          this.isEdit = false;
          this.successMessage = 'Personal details updated successfully.';
          this.toastr.success('Personal details updated successfully', '', {
            timeOut: 3000,
            positionClass: 'toast-top-center'
          });
          this.scrollToTop();
          this.sharedService.setUserUpdate(true);
          this.refreshUser();
          this.reFetchData();
          this.isFormSubmitted = false;

          setTimeout(() => {
            this.successMessage = '';
          }, 6000);
        },
        error:(error:any) => {
          this.isFormSubmitted = false;
          this.errorMessage = error?.error?.message || 'Failed to update personal details. Please try again.';
          this.toastr.error(this.errorMessage, 'Error');
          this.scrollToTop();
        },
      })

    }

  }

  reFetchData() {

    this.userService.apiUserGetUserByUserNameGet(this.sessionService.userEmail).subscribe({
      next:(res:any) => {
        
        this.formData = res.value[0]
        this.userPhone = this.formData.phone ? this.formData.phone : '';
        if (Number(this.formData.userTypeId) === 7 || Number(this.formData.userTypeId) === 5) {
          this.userTypeId = this.formData.userTypeId?.toString();
        } else if (this.formData.roleRecruiter && this.formData.roleBenchSales) {
          this.userTypeId = '3';
        } else if (this.formData.roleBenchSales) {
          this.userTypeId = '2';
        } else if (this.formData.roleRecruiter) {
          this.userTypeId = '1';
        } else {
          this.userTypeId = this.formData.userTypeId?.toString();
        }
        
        const userConsultancy = res.value[0]?.consultancyUsers?.[0]?.consultancy;
        const cid = res.value[0]?.consultancyUsers?.[0]?.consultancyId || this.sessionService.consultancyId;
        if (userConsultancy) {
          this.companyData = { ...userConsultancy };
          this.companyData.website = this.companyData.website || this.companyData.Website || '';
          this.userData.consultancyID = cid;
        } else if (cid) {
          this.consultancyService.apiConsultancyConsultancyByIdGet(cid).subscribe({
            next: (cRes: any) => {
              if (cRes?.value) {
                this.companyData = cRes.value;
                this.companyData.website = this.companyData.website || this.companyData.Website || '';
                this.userData.consultancyID = cid;
              }
            }
          });
        } else {
          this.autoDetectCompanyFromEmail(this.sessionService.userEmail || this.formData?.email);
        }
        
      },
      error:(error:any) => {
 
      }
    })

  }

  ngOnInit() {

    this.userService.apiUserGetUserByUserNameGet(this.sessionService.userEmail).subscribe({
      next:(res:any) => {
        
        this.formData = res.value[0]
        const existingProfileId = res.value[0]?.consultancyUsers?.[0]?.publicProfileUserName
        if (existingProfileId && existingProfileId.trim() !== '') {
          this.initialProfileId = existingProfileId
          this.formData.publicProfileUserName = existingProfileId
        } else {
          this.generateDefaultProfileName(true)
        }
        
        this.userPhone = this.formData.phone ? this.formData.phone : '';
        if (Number(this.formData.userTypeId) === 7 || Number(this.formData.userTypeId) === 5) {
          this.userTypeId = this.formData.userTypeId?.toString();
        } else if (this.formData.roleRecruiter && this.formData.roleBenchSales) {
          this.userTypeId = '3';
        } else if (this.formData.roleBenchSales) {
          this.userTypeId = '2';
        } else if (this.formData.roleRecruiter) {
          this.userTypeId = '1';
        } else {
          this.userTypeId = this.formData.userTypeId?.toString();
        }
        
        const userConsultancy = res.value[0]?.consultancyUsers?.[0]?.consultancy;
        const cid = res.value[0]?.consultancyUsers?.[0]?.consultancyId || this.sessionService.consultancyId;
        if (userConsultancy) {
          this.companyData = { ...userConsultancy };
          this.companyData.website = this.companyData.website || this.companyData.Website || '';
          this.userData.consultancyID = cid;
        } else if (cid) {
          this.consultancyService.apiConsultancyConsultancyByIdGet(cid).subscribe({
            next: (cRes: any) => {
              if (cRes?.value) {
                this.companyData = cRes.value;
                this.companyData.website = this.companyData.website || this.companyData.Website || '';
                this.userData.consultancyID = cid;
              }
            },
            error: (err: any) => {
              console.log(err);
            }
          });
        } else {
          this.autoDetectCompanyFromEmail(this.sessionService.userEmail || this.formData?.email);
        }
        
        console.log(this.formData)
        this.isLoaded = true
        this.isError = false
        

      },
      error:(error:any) => {
        console.log(error)
        this.isLoaded = true
        this.isError = true
        this.error = getMeaningfulErrorMessage(error, 'Unable to load personal details. Please try again.')
      }
    })

    if (this.sessionService.consultancyId) {
      this.consultancyService.apiConsultancyConsultancyByIdGet(this.sessionService.consultancyId).subscribe({
        next: (res:any) => {
          if (res?.value && !this.companyData?.name) {
            this.companyData = res.value;
            this.companyData.website = this.companyData.website || this.companyData.Website || '';
          }
        },
        error: (error:any) => {
          console.log(error);
        }
      });
    }

    this.nameChangeSub = this.nameChange$.pipe(debounceTime(300)).subscribe(() => {
      this.generateDefaultProfileName(true);
    });
  }

  getSkillChips(): string[] {
    if (!this.formData?.myskills) return [];
    return this.formData.myskills
      .split(',')
      .map((s: string) => s.trim())
      .filter((s: string) => s.length > 0);
  }

  ngOnDestroy() {
    if (this.nameChangeSub) {
      this.nameChangeSub.unsubscribe();
    }
  }

}
